### ISSUE TITLE
Wiki help for Fedora

### ISSUE THREAD

**Issue by shoeper** [PHYTEC-Messtechnik-GmbH/phynode-riot-examples#3]
On Fedora I did install the following packages to build OpenOCD and compile the networking example. Maybe you could add it to the documentation (https://github.com/PHYTEC-Messtechnik-GmbH/phynode-riot-examples/wiki/RIOT-getting-started). It took quite some time to find them all. Still likely that I did have some of the dependencies before.

```
To build the examples and OpenOCD installing the following packages can save you some time.
<pre>
sudo dnf install openocd arm-none-eabi-gcc-cs arm-none-eabi-newlib gcc libudev-devel libusbx autoconf automake libtool libusb-devel hidapi-devel texinfo glibc-devel.i686
</pre>
```

**Comment by jremmert-phytec-iot** [comment]
Hi shoeper, 
thanks for the hint! I added the package list to the FAQ section in [1].

[1] - https://github.com/PHYTEC-Messtechnik-GmbH/phynode-riot-examples/wiki/RIOT-getting-started
